Hello Microverse project
ridabensalem/Hello-Microverse pull request #2
Opened 2022-12-01 08:05 UTC by ridabensalem

Update Hello Microverse project

2022-12-01 09:10 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: 

Hi @ridabensalem , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif">

## Highlights
- Good use of Github flow :+1: 
- Good README file :+1: 
- Meaningful commit messages :+1: 

## Required Changes ♻️

- [ ] Kindly make sure, the conflict between the feature and main is solve, to allow future secure merge :small_airplane: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 09:10 UTC, GedeonTS commented on .github/workflow/linter.yml
> +name: Linters
- [ ] Good job trying to set up the linters :+1: , However the workflows are not running, I suggest to to rename the file `linters.yml` instead of `linter.yml`.

2022-12-01 13:10 UTC, ridabensalem commented on .github/workflow/linter.yml
> +name: Linters
@GedeonTS Please I have fixed everything would you mind reviewing it now?

2022-12-02 06:58 UTC, DuaneDave approved these changes
Hi @ridabensalem 👋,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Linters are passing 💯 
✔️ Quick application of changes 👍


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 07:53 UTC, merged